<main id="sklad">
	<h1>Historie</h1>
	<div id="vyhledavani_datum">
		<div>
			<label for="datum_od">Datum od</label>
			<input type="date" id="datum_od" name="datum_od" value="2019-01-01"> 
		</div>
		<div>
			<label for="datum_do">Datum do</label>
			<input type="date" id="datum_do" name="datum_do"> 
		</div>
	</div>
	<div style="clear:both"></div>
	<table id="tabulka_zbozi">
		<tr>
	        <th>Datum</th>
	        <th>Typ</th>
	    	<? if($nastaveni['nazev']){ ?>
	        <th><?= "Název";} ?></th>
	    	<? if($nastaveni['dodavatel']){ ?>
	        <th><?= "Dodavatel";} ?></th>
	    	<? if($nastaveni['cena_nakupni']){ ?>
	        <th><?= "Nákupní cena";} ?></th>
	    	<? if($nastaveni['cena_prodejni']){ ?>
	        <th><?= "Prodejní cena";} ?></th>
	    	<? if($nastaveni['mj']){ ?>
	        <th><?= "MJ";} ?></th>
	    	<? if($nastaveni['mnozstvi']){ ?>
	        <th><?= "Mno¾ství";} ?></th>
	        <th>Poznámka k dodávce</th>
		</tr>
	<?php foreach ($dodavky as $dodavka) : ?>
	    	<? for($i = 0; $i < count($dodavka)-3; $i++){ ?>
	    	<? $trida = $i == count($dodavka)-4? "class=\"spodni_ramecek\"" : "" ?>
	    <tr <?= $trida ?>>
	    	<? if($i == 0){ ?>
	        <td rowspan="<?= count($dodavka)-3 ?>" class="spodni_ramecek">
	            <?= $dodavka['datum'] ?>
	        </td>
	        <td rowspan="<?= count($dodavka)-3 ?>" class="pravy_ramecek spodni_ramecek">	            
	            <?= $dodavka['smer'] ?>
	        </td>
	        <? } ?>

			<? if($nastaveni['nazev']){ ?>
			<td><?= $dodavka[$i]['nazev'];} ?></td>
			<? if($nastaveni['dodavatel']){ ?>
			<td><?= $dodavka[$i]['dodavatel'];} ?></td>
			<? if($nastaveni['cena_nakupni'] == 1){ ?>
			<td><?= $dodavka[$i]['cena_nakupni'];} ?></td>
			<? if($nastaveni['cena_prodejni']){ ?>
			<td><?= $dodavka[$i]['cena_prodejni'];} ?></td>
			<? if($nastaveni['mj']){ ?>
			<td><?= $dodavka[$i]['mj'];} ?></td>
			<? if($nastaveni['mnozstvi']){ ?>
			<td><?= $dodavka[$i]['mnozstvi'];} ?></td>

	    	<? if($i == 0){ ?>

	        <td rowspan="<?= count($dodavka)-3 ?>" class="levy_ramecek spodni_ramecek">          
	            <?= $dodavka['poznamka'] ?>
	        </td>

	        <? } ?>
	    </tr>

        <? } ?>
	<?php endforeach ?>
	</table>
</main>

<script>
	
window.onload = today_date_to_form;

function today_date_to_form(){
        n =  new Date();
        y = n.getFullYear();
        m = n.getMonth() + 1;
        d = ("0" + n.getDate()).slice(-2);
        document.getElementById("datum_do").value = y + "-" + m + "-" + d;
}
	
</script>