<main id="sklad">
	<? if($spatne_heslo == 1){ ?>
    <h2 class='error_for_user'>©patné pøihla¹ovací údaje!</h2>
    <? } ?>
	<? if(isset($_SESSION['reg']) && isset($_SESSION) && $_SESSION['reg'] == 1){ ?>
    <h2 class='message_for_user'>Úspì¹nì zaregistrován!</h2>
    <? } ?>
	<div id="login">
	    <form method="post">
	        <h2>Pøihlá¹ení</h2>
	        <p class="hint">U¾ivatelské jméno:</p>
	        <input type="text" name="username" placeholder="login"/ autofocus>
	        <p class="hint">Heslo:</p>
	        <input type="password" name="password" placeholder="heslo"/>
	        <input type="submit" name="login" value="Pøihlásit">
	    </form>
	</div>
	<div id="no_account">Stále nemáte úèet? <a href="?akce=registrace">Zaregistrovat!</a></div>

</main>