<main id="sklad">
	<? if($reg == 1){ ?>
    <h2 class='message_for_user'>Úspì¹nì zaregistrován!</h2>
    <? } ?>

	<div id="login">
    <form method="post">
        <h2>Registrace</h2>
        <p class="hint">U¾ivatelské jméno:</p>
        <input type="text" name="username" placeholder="login"/>
        <p class="hint">Heslo:</p>
        <input type="password" name="password" placeholder="heslo"/>
        <input type="submit" name="registration" value="Zaregistrovat">
    </form>
</div>
</main>