<!DOCTYPE html>
<html lang="cs">
<head>
    <meta http-equiv="content-type" content="text/html;" charset="ISO-8859-2"/>
    
    <link rel="stylesheet" type="text/css" href="css/index.css">
    <link rel="stylesheet" type="text/css" href="css/sklad.css">
    <link rel="stylesheet" type="text/css" href="css/prijem.css">
    <link rel="stylesheet" type="text/css" href="css/vydej.css">
    <link rel="stylesheet" type="text/css" href="css/historie.css">
    <link rel="stylesheet" type="text/css" href="css/nastaveni.css">
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>Inventory manager</title>
</head>
<body>
    <header>

    </header>
        <?php $this->kontroler->vypisPohled(); // vložení aktuálního pohledu do šablony ?>
    <footer>
        
    </footer>
</body>
</html>